[c2_setup]
c2_target ansible_host=ec2-13-53-143-13.eu-north-1.compute.amazonaws.com ansible_user=ubuntu ansible_private_key_file=/home/ageent/projects/infra-kes7a/c2_server/draft/c2_key.pem

[all:vars]
# No specific vars needed for this setup
