[c2_setup]
c2_target ansible_host=ec2-13-51-72-68.eu-north-1.compute.amazonaws.com ansible_user=ubuntu ansible_private_key_file=/home/ageent/draft/terraform/c2_key.pem

[all:vars]
# No specific vars needed for this setup
